{
 "title": "New dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Free RAM",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "(node_memory_MemFree_bytes{instance=\"nodeexporter:9100\",job=\"nodeexporter\"})"
    }
   ]
  },
  {
   "title": "CPU LA 1min",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(node_load1{instance=\"nodeexporter:9100\",job=\"nodeexporter\"}) /  count(count(node_cpu_seconds_total{instance=\"nodeexporter:9100\",job=\"nodeexporter\"}) by (cpu)) * 100",
     "legendFormat": "cpula 1min"
    }
   ]
  },
  {
   "title": "CPU LA 5min",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(node_load5{instance=\"nodeexporter:9100\",job=\"nodeexporter\"}) /  count(count(node_cpu_seconds_total{instance=\"nodeexporter:9100\",job=\"nodeexporter\"}) by (cpu)) * 100",
     "legendFormat": "cpu la 5min"
    }
   ]
  },
  {
   "title": "CPU util",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"nodeexporter\",mode=\"idle\"}[1m])) * 100)"
    }
   ]
  },
  {
   "title": "CPU LA 15min",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(node_load15{instance=\"nodeexporter:9100\",job=\"nodeexporter\"}) /  count(count(node_cpu_seconds_total{instance=\"nodeexporter:9100\",job=\"nodeexporter\"}) by (cpu)) * 100",
     "legendFormat": "cpu la 15min"
    }
   ]
  },
  {
   "title": "Free space on the FS.",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (100 * ((node_filesystem_avail_bytes{instance=\"nodeexporter:9100\",mountpoint=\"/\",fstype!=\"rootfs\"} )  / (node_filesystem_size_bytes{instance=\"nodeexporter:9100\", mountpoint=\"/\",fstype!=\"rootfs\"}) ))"
    }
   ]
  }
 ]
}