apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment2
  labels:
    app: deployment2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment2
  template:
    metadata:
      labels:
        app: deployment2
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
      initContainers:
      - name: busybox
        image: busybox
        command: ['sh', '-c', "until nslookup nginx.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for nginx; sleep 2; done"]