apiVersion: v1
kind: Service
metadata:
  name: svc-nginx-multitool
spec:
  selector:
    app: deployment1
  ports:
  - name: nginx
    port: 8888
    targetPort: 80
  - name: multitool
    port: 7777
    targetPort: 8080