pipeline {
    agent{
    label "agent"
    }
    stages {
        stage ('Clone repository'){
            steps {
                git branch: 'master', url: 'https://github.com/mingaliev-e/vector-role.git'
            }
        }
        stage ('molecule test'){
            steps {
                sh '''
                    export PATH=$PATH:/usr/local/bin
                    cd vector-role
                    molecule test
                '''
            }
        }
    }
}
