stages:
  - test
  - build
  - deploy

variables:
  DOCKER_IMAGE: "m222777/zbx-tg_assistent-bot"

testing:
  stage: test
  script:
    - shopt -s globstar && python3.8 -m py_compile ./**/*.py
  tags:
    - netology

build:
  stage: build
  script:
    - docker login -u "${DOCKER_USER}" -p "${DOCKER_PASS}"
    - DOCKER_TAG="${CI_COMMIT_TAG:-latest}"
    - docker build -t $DOCKER_IMAGE .
    - docker tag $DOCKER_IMAGE $DOCKER_IMAGE:$DOCKER_TAG
    - docker tag $DOCKER_IMAGE $DOCKER_IMAGE:latest
    - docker push $DOCKER_IMAGE:$DOCKER_TAG
    - docker push $DOCKER_IMAGE:latest
  tags:
    - netology
  only:
    - tags

deploy:
  stage: deploy
  script:
    - envsubst < app.yml | sudo kubectl apply -f -
  tags:
    - netology
  only:
    - tags