apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment1
  labels:
    app: nginx-mtl
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-mtl
  template:
    metadata:
      labels:
        app: nginx-mtl
    spec:
      containers:
      - name: nginx
        image: nginx
        env:
        - name: HTTP_PORT
          value: "80"
      - name: multitool
        image: wbitt/network-multitool
        env:
        - name: HTTP_PORT
          value: "8080"