apiVersion: v1
kind: Service
metadata:
  name: svc-cluster-ip
spec:
  selector:
    app: nginx-mtl
  type: ClusterIP
  ports:
  - name: nginx
    port: 9001
    targetPort: 80
  - name: multitool
    port: 9002
    targetPort: 8080
