apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment1
  labels:
    app: nginx-mtl
spec:
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 4
      maxUnavailable: 4
  selector:
    matchLabels:
      app: nginx-mtl
  template:
    metadata:
      labels:
        app: nginx-mtl
    spec:
      containers:
      - name: nginx
        image: nginx:1.20
        ports:
        - containerPort: 80
      - name: multitool
        image: wbitt/network-multitool
        env:
        - name: HTTP_PORT
          value: "8080"
        - name: HTTPS_PORT
          value: "443"
        ports:
        - containerPort: 8080
          name: http-port
        - containerPort: 443
          name: https-port:wq
