apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-multitool
  labels:
    app: busybox-multitool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox-multitool
  template:
    metadata:
      labels:
        app: busybox-multitool
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["/bin/sh", "-c", "while true; do echo $(date) 'Hello, Multitool!' >> /write/file.txt; sleep 5; done"]
        volumeMounts:
          - name: locale-volume
            mountPath: "/write"
      - name: multitool
        image: praqma/network-multitool
        volumeMounts:
          - name: locale-volume
            mountPath: "/read"
        env:
        - name: HTTP_PORT
          value: "8080"
      volumes:
        - name: locale-volume
          persistentVolumeClaim:
            claimName: locale-pvc