apiVersion: apps/v1
kind: Deployment
metadata:
  name: zbx-assistent-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zbx-assistent
  template:
    metadata:
      labels:
        app: zbx-assistent
    spec:
      containers:
      - name: zbx-assistent
        image: m222777/zbx-tg_assistent-bot:latest
        env:
        - name: BOT_TOKEN
          value: "${BOT_TOKEN}"
        - name: ZABBIX_URL
          value: "${ZABBIX_URL}"

---
apiVersion: v1
kind: Service
metadata:
  name: zbx-assistent-service
spec:
  selector:
    app: zbx-assistent
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80